version: '3.7'

services:
  hub:
    build: hub
    container_name: hub
    image: plasmabio-hub
    restart: on-failure
    environment:
      - DOCKER_NETWORK_NAME
    networks:
      - plasmabio
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # TODO: remove and replace by CAS Authenticator
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro

networks:
  plasmabio:
    name: '${DOCKER_NETWORK_NAME}'
