---

plasmabio_repo: https://github.com/plasmabio/plasmabio
plasmabio_remote_dest: /srv/plasmabio

tljh_config_dir: /opt/tljh/hub/config/jupyterhub_config.d
tljh_installer_url: https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/skip-install/bootstrap/bootstrap.py
tljh_installer_dest: /srv/tljh-installer.py
...