defaultentrypoints = ["http"]

# the defaullogLevel = "INFO"
# log errors, which could be proxy errors
[accessLog]
format = "json"
[accessLog.filters]
statusCodes = ["500-999"]

# the api entrypoint
[api]
dashboard = true
entrypoint = "auth_api"

# websocket protocol
[wss]
protocol = "http"

# the port on localhost where traefik accepts http requests
[entryPoints.http]
address = ":8000"

# the port on localhost where the traefik api and dashboard can be found
[entryPoints.auth_api]
address = ":8099"

# authenticate the traefik api entrypoint
[entryPoints.auth_api.auth.basic]
# TODO: handle secrets. These can be generated automatically
users = [ "foo:$apr1$KDDFbUp8$BVWhX1ig6mkwkgbS8Xoxd.",]

# the dynamic configuration file
[file]
filename = "/etc/traefik/rules.toml"
watch = true
