---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:

    - name: Reset the list of admin users to avoid duplicates
      shell: tljh-config unset users.admin

    - name: Add admin users
      shell: tljh-config add-item users.admin {{ item }}
      loop: "{{ admins }}"

    - name: Reload the hub
      shell: "tljh-config reload hub"
