---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Add eoan-backports repository to be able to install cockpit-docker
      apt_repository:
        repo: deb http://fr.archive.ubuntu.com/ubuntu eoan-backports main universe
        state: present
      when: ansible_distribution_release == 'focal'

    - name: Install Cockpit with the Docker plugin
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'cockpit', 'cockpit-docker' ]

    - name: Create the cockpit config
      copy:
        dest: "/etc/cockpit/cockpit.conf"
        content: |
          [WebService]
          Origins = https://{{ name_server }} wss://{{ name_server }}
          ProtocolHeader = X-Forwarded-Proto

          # Cockpit is added as a JupyterHub service so the rules are added to Traefik
          UrlRoot=/services/cockpit/

          # SSL termination is done on the Traefik proxy
          AllowUnencrypted=true

    - name: Ensure cockpit is running
      systemd:
        name: cockpit
        state: started
        daemon_reload: yes

    # Restart JupyterHub to add the cockpit service
    - name: Restart the hub
      shell: "tljh-config reload hub"
