exclude:
  - root
  - daemon
  - bin
  - sys
  - adm
  - tty
  - disk
  - lp
  - mail
  - news
  - uucp
  - man
  - proxy
  - kmem
  - dialout
  - fax
  - voice
  - cdrom
  - floppy
  - tape
  - sudo
  - audio
  - dip
  - www-data
  - backup
  - operator
  - list
  - irc
  - src
  - gnats
  - shadow
  - utmp
  - video
  - sasl
  - plugdev
  - staff
  - games
  - users
  - nogroup
  - systemd-journal
  - systemd-timesync
  - systemd-network
  - systemd-resolve
  - crontab
  - messagebus
  - input
  - kvm
  - render
  - syslog
  - uuidd
  - tcpdump
  - ssh
  - landscape
  - admin
  - netdev
  - lxd
  - systemd-coredump
  - ubuntu
  - docker
  - jupyterhub-admins
  - jupyterhub-users
  - cockpit-ws
