---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Ensure the groups exist
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ plasma_groups }}"

    - name: Reset the list of allowed UNIX groups to avoid duplication
      shell: tljh-config unset user_groups
      register: groups
      failed_when: groups.rc > 1

    - name: Configure the list of UNIX groups
      shell: tljh-config add-item plasma.groups {{ item }}
      loop: "{{ plasma_groups }}"

    - name: Reload the hub
      shell: "tljh-config reload hub"
