---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'curl', 'python3', 'python3-dev', 'python3-pip']

    - name: Download the TLJH installer
      get_url:
        url: "{{ tljh_installer_url }}"
        dest: "{{ tljh_installer_dest }}"

    - name: Check if the tljh-plasmabio is already installed
      shell: "{{ tljh_prefix }}/hub/bin/python3 -c 'import tljh_plasmabio'"
      register: tljh_plasmabio_installed
      failed_when: tljh_plasmabio_installed.rc != 0 or tljh_plasmabio_installed.rc != 1

    - name: Upgrade the tljh-plasmabio plugin first if it is already installed
      shell: "{{ tljh_prefix }}/hub/bin/pip3 install --upgrade {{ tljh_plasmabio }}"
      when: tljh_plasmabio_installed.rc == 0

    - name: Run the TLJH installer
      shell: "{{ ansible_python_interpreter }} {{ tljh_installer_dest }} --no-user-env --plugin {{ tljh_plasmabio }}"
      # TODO: remove when --no-user-env (or equivalent) is available
      environment:
        TLJH_BOOTSTRAP_PIP_SPEC: "{{ tljh_bootstrap_pip_spec }}"

    - name: Set the idle culler timeout to 1 hour
      shell: "tljh-config set services.cull.timeout 3600"

    - name: Reload the hub
      shell: "tljh-config reload hub"

    # Pull the repo2docker image to build user images
    - name: Pull jupyter/repo2docker
      docker_image:
        name: jupyter/repo2docker
        tag: master
        source: pull
