---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'curl', 'python3', 'python3-dev', 'python3-pip']

    - name: Download the TLJH installer
      get_url:
        url: "{{ tljh_installer_url }}"
        dest: "{{ tljh_installer_dest }}"

    - name: Run the TLJH installer
      shell: "python3 {{ tljh_installer_dest }} --no-user-env"
      # TODO: remove when --no-user-env (or equivalent) is available
      environment:
        TLJH_BOOTSTRAP_PIP_SPEC: "{{ tljh_bootstrap_pip_spec }}"
