---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'curl', 'python3', 'python3-dev', 'python3-pip']

    - name: Fetch the plasmabio project
      git:
        repo: "{{ plasmabio_repo }}"
        dest: "{{ plasmabio_remote_dest }}"
        version: master

    - name: Ensure the TLJH config directory exists
      file:
        path: "{{ tljh_config_dir }}"
        state: directory

    - name: Move the JupyterHub config to the right folder
      copy:
        src: "{{ plasmabio_remote_dest }}/hub/jupyterhub_config.py"
        dest: "{{ tljh_config_dir }}/jupyterhub_config.py"
        remote_src: yes

    - name: Download the TLJH installer
      get_url:
        url: "{{ tljh_installer_url }}"
        dest: "{{ tljh_installer_dest }}"

    # TODO: specify dockerspawner dependency for the hub
    - name: Run the TLJH installer
      shell: "python3 {{ tljh_installer_dest }} --hub-only"