---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Add Test User
      user:
        name: foo
        password: $6$z1YHU3S9Id0BvRL7$Nk/Vukh/Bx0HEW/hWvHjDVLYWO2vv4ZY2RC5nc2yehfGg8k6jnhIXvfk6zA/zAUG1TgN.diV/WFFiJOphYoXl.
        shell: /bin/bash
